#http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
version: "3"
services:
  mapperson:
    build: .
    command: "node_modules/.bin/nodemon src/server/index.js &&  tail -f /dev/null"
    environment:
      NODE_ENV: development
    ports:
      - '8001:8001'
    tty: true
    depends_on: 
      - mongo
    volumes:
      - .:/home/app/mapperson
      - /home/app/mapperson/node_modules
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example